### ISSUE TITLE
all_properties has no parameter called "page_limit"

### ISSUE THREAD

**Issue by 007-JB** [imrankhan17/pyzoopla#5]
TypeError: all_properties() got an unexpected keyword argument 'page_limit'

Opening your file shows the following:

    def all_properties(self, page_start=None, page_end=None):
        """
        List of all property ID's for specified location.
        :param page_start: page no. to start scraping from
        :param page_end: page no. to scrape till
        :return: list of ID's
        """

        page_start = page_start if page_start else 1
        page_end = page_end if page_end else self.total_pages + 1

        if page_end == 1:.....

But your example states:
"results.all_properties(page_limit=1)"

SEARCHING your code for page_limit yields nothing.

Further, I'm able to retrieve aggregate detail such as this:

results.market_activity()
{'period': 20, 'property_type': 'all', 'average_price': 217189, 'num_sales': 323350, 'average_value': 334743, 'value_change': 224485}

But the results.all_properties consistently returns an empty string (even if I specify appropriate start and end pages- which look like the only two arguments permissible:

results.all_properties(1,4)
[]

Will raise as separate issue//////

**Comment by imrankhan17** [comment]
Fixed with https://github.com/imrankhan17/pyzoopla/commit/4e0de8a8e8d5a0576e9fa8796d4c9afe82842627
