### ISSUE TITLE
no ids being returned with results.all_properties(page_start, page_end)

### ISSUE THREAD

**Issue by 007-JB** [imrankhan17/pyzoopla#6]
Receive the following output when running this code:

from pyzoopla.prices import PricesSearch

results = PricesSearch(location='bs')
print(results)
print(results.assumed_search_location)
print(results.market_activity(period=1, ))
print(results.total_pages)
print(results.total_properties)
print(results.all_properties(page_start=1, page_end=4))

**output**

https://www.zoopla.co.uk/house-prices/bs/
BS
{'period': 1, 'property_type': 'all', 'average_price': 340603, 'num_sales': 7204, 'average_value': 334743, 'value_change': 27535}
10935
437387
[]

**Comment by 007-JB** [comment]
Please help! I love the initiative otherwise.... keep it up mate!!

**Comment by 007-JB** [comment]
No feedback on this yet??
pls help!

**Comment by imrankhan17** [comment]
Fixed with https://github.com/imrankhan17/pyzoopla/commit/eee241209fdf0f3dae3aad09fc433ace49f1abf8

Try again after `pip install -U pyzoopla`
